version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: waste-compliance-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-waste_compliance}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - waste-compliance-network

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: waste-compliance-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-waste_compliance}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      AI_MOCK_MODE: ${AI_MOCK_MODE:-true}
      MODEL_ENDPOINT: ${MODEL_ENDPOINT:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      # Mount source code for development (comment out for production)
      - ./src:/app/src:ro
    networks:
      - waste-compliance-network
    command: node src/server.js

  # PgAdmin - Database Administration UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: waste-compliance-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@waste-compliance.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - waste-compliance-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  waste-compliance-network:
    driver: bridge
